export const commands = [
    // --- 🌸 Anime & Reacciones ---
    {"name": "angry", "alias": ["/angry"], "category": "anime", "desc": "Muestra que estas molesto."},
    {"name": "bleh", "alias": ["/bleh"], "category": "anime", "desc": "Saca la lengua."},
    {"name": "bored", "alias": ["/bored"], "category": "anime", "desc": "Estás aburrido."},
    {"name": "kiss", "alias": ["/kiss"], "category": "anime", "desc": "Besa a alguien."},
    {"name": "clap", "alias": ["/clap"], "category": "anime", "desc": "Aplaude."},
    {"name": "coffee", "alias": ["/coffee"], "category": "anime", "desc": "Toma café."},
    {"name": "dramatic", "alias": ["/dramatic"], "category": "anime", "desc": "Modo dramático."},
    {"name": "drunk", "alias": ["/drunk"], "category": "anime", "desc": "Estás borracho."},
    {"name": "impregnate", "alias": ["/impregnate"], "category": "anime", "desc": "Embaraza a alguien."},
    {"name": "laugh", "alias": ["/laugh"], "category": "anime", "desc": "Ríete."},
    {"name": "love", "alias": ["/love"], "category": "anime", "desc": "Muestra amor."},
    {"name": "pout", "alias": ["/pout"], "category": "anime", "desc": "Haz pucheros."},
    {"name": "punch", "alias": ["/punch"], "category": "anime", "desc": "Golpea a alguien."},
    {"name": "run", "alias": ["/run"], "category": "anime", "desc": "Corre."},
    {"name": "sad", "alias": ["/sad"], "category": "anime", "desc": "Estás triste."},
    {"name": "scared", "alias": ["/scared"], "category": "anime", "desc": "Tienes miedo."},
    {"name": "seduce", "alias": ["/seduce"], "category": "anime", "desc": "Seduce a alguien."},
    {"name": "shy", "alias": ["/shy"], "category": "anime", "desc": "Timidez."},
    {"name": "sleep", "alias": ["/sleep"], "category": "anime", "desc": "Duerme."},
    {"name": "smoke", "alias": ["/smoke"], "category": "anime", "desc": "Fuma."},
    {"name": "spit", "alias": ["/spit"], "category": "anime", "desc": "Escupe."},
    {"name": "step", "alias": ["/step"], "category": "anime", "desc": "Pisa a alguien."},
    {"name": "think", "alias": ["/think"], "category": "anime", "desc": "Piensa."},
    {"name": "walk", "alias": ["/walk"], "category": "anime", "desc": "Camina."},
    {"name": "hug", "alias": ["/hug"], "category": "anime", "desc": "Abraza a alguien."},
    {"name": "kill", "alias": ["/kill"], "category": "anime", "desc": "Mata a alguien."},
    {"name": "eat", "alias": ["/eat"], "category": "anime", "desc": "Come."},
    {"name": "wink", "alias": ["/wink"], "category": "anime", "desc": "Guiña el ojo."},
    {"name": "pat", "alias": ["/pat"], "category": "anime", "desc": "Acaricia."},
    {"name": "happy", "alias": ["/happy"], "category": "anime", "desc": "Estás feliz."},
    {"name": "bully", "alias": ["/bully"], "category": "anime", "desc": "Haz bullying."},
    {"name": "bite", "alias": ["/bite"], "category": "anime", "desc": "Muerde."},
    {"name": "blush", "alias": ["/blush"], "category": "anime", "desc": "Sonrójate."},
    {"name": "wave", "alias": ["/wave"], "category": "anime", "desc": "Saluda."},
    {"name": "bath", "alias": ["/bath"], "category": "anime", "desc": "Báñate."},
    {"name": "smug", "alias": ["/smug"], "category": "anime", "desc": "Presume."},
    {"name": "smile", "alias": ["/smile"], "category": "anime", "desc": "Sonríe."},
    {"name": "highfive", "alias": ["/highfive"], "category": "anime", "desc": "Choca los cinco."},
    {"name": "handhold", "alias": ["/handhold"], "category": "anime", "desc": "Toma la mano."},
    {"name": "cringe", "alias": ["/cringe"], "category": "anime", "desc": "Vergüenza ajena."},
    {"name": "bonk", "alias": ["/bonk"], "category": "anime", "desc": "Golpe suave."},
    {"name": "cry", "alias": ["/cry"], "category": "anime", "desc": "Llora."},
    {"name": "lick", "alias": ["/lick"], "category": "anime", "desc": "Lame."},
    {"name": "slap", "alias": ["/slap"], "category": "anime", "desc": "Abofetea."},
    {"name": "dance", "alias": ["/dance"], "category": "anime", "desc": "Baila."},
    {"name": "cuddle", "alias": ["/cuddle"], "category": "anime", "desc": "Acurrúcate."},
    {"name": "cold", "alias": ["/cold"], "category": "anime", "desc": "Tienes frío."},
    {"name": "sing", "alias": ["/sing"], "category": "anime", "desc": "Canta."},
    {"name": "tickle", "alias": ["/tickle"], "category": "anime", "desc": "Cosquillas."},
    {"name": "scream", "alias": ["/scream"], "category": "anime", "desc": "Grita."},
    {"name": "push", "alias": ["/push"], "category": "anime", "desc": "Empuja."},
    {"name": "nope", "alias": ["/nope"], "category": "anime", "desc": "Niega."},
    {"name": "jump", "alias": ["/jump"], "category": "anime", "desc": "Salta."},
    {"name": "heat", "alias": ["/heat"], "category": "anime", "desc": "Tienes calor."},
    {"name": "gaming", "alias": ["/gaming"], "category": "anime", "desc": "Juega."},
    {"name": "draw", "alias": ["/draw"], "category": "anime", "desc": "Dibuja."},
    {"name": "call", "alias": ["/call"], "category": "anime", "desc": "Llama."},
    {"name": "snuggle", "alias": ["/snuggle"], "category": "anime", "desc": "Acurrúcate fuerte."},
    {"name": "blowkiss", "alias": ["/blowkiss"], "category": "anime", "desc": "Lanza un beso."},
    {"name": "trip", "alias": ["/trip"], "category": "anime", "desc": "Tropieza."},
    {"name": "stare", "alias": ["/stare"], "category": "anime", "desc": "Mira fijamente."},
    {"name": "sniff", "alias": ["/sniff"], "category": "anime", "desc": "Olfatea."},
    {"name": "curious", "alias": ["/curious"], "category": "anime", "desc": "Curiosidad."},
    {"name": "comfort", "alias": ["/comfort"], "category": "anime", "desc": "Consuela."},
    {"name": "peek", "alias": ["/peek"], "category": "anime", "desc": "Espía."},

    // --- 🔎 Búsquedas ---
    {"name": "pinterest", "alias": ["/pin"], "category": "search", "desc": "Busca en Pinterest."},
    {"name": "imagen", "alias": ["/img", "/image"], "category": "search", "desc": "Busca en Google."},
    {"name": "aptoide", "alias": ["/apk", "/apkdl"], "category": "search", "desc": "Descarga apps."},
    {"name": "ytsearch", "alias": ["/yts"], "category": "search", "desc": "Busca en YouTube."},
    {"name": "tiktoksearch", "alias": ["/ttsearch", "/tsearch"], "category": "search", "desc": "Busca en TikTok."},
    {"name": "tts", "alias": ["/texttospeech"], "category": "search", "desc": "Texto a voz."},

    // --- 📥 Descargas ---
    {"name": "facebook", "alias": ["/fb"], "category": "download", "desc": "Video de Facebook."},
    {"name": "instagram", "alias": ["/ig", "/igdl", "/instadl"], "category": "download", "desc": "Video de Instagram."},
    {"name": "tiktok", "alias": ["/tt", "/tiktokdl", "/ttdl"], "category": "download", "desc": "Video de TikTok."},
    {"name": "play", "alias": ["/play2", "/playaudio", "/playvideo", "/mp3", "/mp4", "/ytmp3", "/ytmp4"], "category": "download", "desc": "Música/Video YouTube."},
    {"name": "spotify", "alias": ["/spot"], "category": "download", "desc": "Música Spotify."},
    {"name": "mediafire", "alias": ["/mf"], "category": "download", "desc": "Archivo Mediafire."},
    {"name": "mega", "alias": ["/mg"], "category": "download", "desc": "Archivo Mega."},
    {"name": "modapk", "alias": ["/apkmod"], "category": "download", "desc": "APK Modificado."},
    {"name": "twitter", "alias": ["/x", "/xtt", "/xtwitter"], "category": "download", "desc": "Video de Twitter/X."},
    {"name": "gitclone", "alias": ["/git"], "category": "download", "desc": "Clonar Repo GitHub."},
    {"name": "drive", "alias": ["/gdrive"], "category": "download", "desc": "Google Drive."},

    // --- 💰 Economía ---
    {"name": "balance", "alias": ["/bal"], "category": "economia", "desc": "Ver saldo."},
    {"name": "steal", "alias": ["/rob", "/robar"], "category": "economia", "desc": "Robar monedas."},
    {"name": "crime", "alias": ["/crimen"], "category": "economia", "desc": "Cometer crimen."},
    {"name": "givecoins", "alias": ["/pay", "/coinsgive", "/darplata"], "category": "economia", "desc": "Dar monedas."},
    {"name": "ppt", "alias": ["/piedrapapeltijera"], "category": "economia", "desc": "Piedra Papel Tijera."},
    {"name": "math", "alias": ["/matematicas"], "category": "economia", "desc": "Resolver mates."},
    {"name": "waittimes", "alias": ["/cooldowns", "/economyinfo", "/einfo"], "category": "economia", "desc": "Ver tiempos."},
    {"name": "economyboard", "alias": ["/baltop", "/eboard"], "category": "economia", "desc": "Top millonarios."},
    {"name": "slut", "alias": [], "category": "economia", "desc": "Trabajo nocturno."},
    {"name": "mine", "alias": ["/minar"], "category": "economia", "desc": "Minar."},
    {"name": "rt", "alias": ["/roulette", "/ruleta"], "category": "economia", "desc": "Ruleta."},
    {"name": "coinflip", "alias": ["/flip", "/cf"], "category": "economia", "desc": "Cara o Cruz."},
    {"name": "daily", "alias": ["/diario"], "category": "economia", "desc": "Diario."},
    {"name": "monthly", "alias": ["/mensual"], "category": "economia", "desc": "Mensual."},
    {"name": "weekly", "alias": ["/semanal"], "category": "economia", "desc": "Semanal."},
    {"name": "work", "alias": ["/w"], "category": "economia", "desc": "Trabajar."},
    {"name": "deposit", "alias": ["/dep", "/d"], "category": "economia", "desc": "Depositar."},
    {"name": "withdraw", "alias": ["/with", "/retirar"], "category": "economia", "desc": "Retirar."},
    {"name": "logros", "alias": [], "category": "economia", "desc": "Ver logros."},
    {"name": "toplogros", "alias": [], "category": "economia", "desc": "Top logros."},

    // --- 🎲 Gacha (De "Otros" en tu lista) ---
    {"name": "rw", "alias": ["/roll", "/rollwaifu", "/rf"], "category": "gacha", "desc": "Girar waifu."},
    {"name": "c", "alias": ["/claim", "/buy"], "category": "gacha", "desc": "Reclamar waifu."},
    {"name": "harem", "alias": ["/miswaifus", "/claims"], "category": "gacha", "desc": "Tu colección."},
    {"name": "sell", "alias": ["/vender", "/removesale"], "category": "gacha", "desc": "Vender waifu."},
    {"name": "buyc", "alias": ["/buycharacter", "/buychar"], "category": "gacha", "desc": "Comprar waifu tienda."},
    {"name": "trade", "alias": ["/cambiar"], "category": "gacha", "desc": "Intercambiar."},
    {"name": "animelist", "alias": ["/slist", "/serielist"], "category": "gacha", "desc": "Lista de series."},
    {"name": "animeinfo", "alias": ["/ainfo", "/serieinfo"], "category": "gacha", "desc": "Info anime."},
    {"name": "tiendawaifus", "alias": ["/wshop", "/haremshop"], "category": "gacha", "desc": "Tienda."},
    {"name": "delrw", "alias": ["/delwaifu", "/delp"], "category": "gacha", "desc": "Borrar waifu."},
    {"name": "removerventa", "alias": ["/retirarventa"], "category": "gacha", "desc": "Quitar de venta."},
    {"name": "darrw", "alias": ["/givewaifu", "/givechar"], "category": "gacha", "desc": "Regalar waifu."},
    {"name": "giveallharem", "alias": [], "category": "gacha", "desc": "Regalar todo."},
    {"name": "ginfo", "alias": ["/infogacha", "/gachainfo"], "category": "gacha", "desc": "Info gacha."},
    {"name": "verpersonaje", "alias": ["/vp"], "category": "gacha", "desc": "Ver personaje."},
    {"name": "character", "alias": ["/charinfo", "/cinfo"], "category": "gacha", "desc": "Info carta."},
    {"name": "vote", "alias": ["/votar"], "category": "gacha", "desc": "Votar waifu."},
    {"name": "accepttrade", "alias": ["/aceptarintercambio"], "category": "gacha", "desc": "Aceptar cambio."},
    {"name": "waifusboard", "alias": ["/waifustop", "/toprw"], "category": "gacha", "desc": "Top coleccionistas."},
    {"name": "votesboard", "alias": ["/topvotos", "/topwaifus"], "category": "gacha", "desc": "Waifus top."},
    {"name": "wimage", "alias": ["/charimage", "/cimage"], "category": "gacha", "desc": "Imagen waifu."},

    // --- 👥 Grupo ---
    {"name": "mute", "alias": [], "category": "grupo", "desc": "Silenciar bot."},
    {"name": "promote", "alias": ["/admin"], "category": "grupo", "desc": "Dar admin."},
    {"name": "demote", "alias": ["/quitaradmin"], "category": "grupo", "desc": "Quitar admin."},
    {"name": "transfer", "alias": [], "category": "grupo", "desc": "Transferir datos."},
    {"name": "setprimary", "alias": [], "category": "grupo", "desc": "Bot primario."},
    {"name": "setgpbaner", "alias": ["/setgpbanner"], "category": "grupo", "desc": "Foto grupo."},
    {"name": "setgpname", "alias": [], "category": "grupo", "desc": "Nombre grupo."},
    {"name": "setgpdesc", "alias": [], "category": "grupo", "desc": "Desc grupo."},
    {"name": "closet", "alias": [], "category": "grupo", "desc": "Cerrar grupo."},
    {"name": "open", "alias": [], "category": "grupo", "desc": "Abrir grupo."},
    {"name": "delete", "alias": ["/del"], "category": "grupo", "desc": "Borrar mensaje."},
    {"name": "on", "alias": ["/welcome", "/antilink", "/nsfw", "/rpg", "/economia"], "category": "grupo", "desc": "Activar opciones."},
    {"name": "off", "alias": [], "category": "grupo", "desc": "Desactivar opciones."},
    {"name": "groupinfo", "alias": ["/gp"], "category": "grupo", "desc": "Info grupo."},
    {"name": "tag", "alias": ["/hidetag", "/notificar"], "category": "grupo", "desc": "Invocar todos."},
    {"name": "kick", "alias": ["/ban"], "category": "grupo", "desc": "Expulsar."},
    {"name": "warn", "alias": ["/warns"], "category": "grupo", "desc": "Advertencias."},
    {"name": "delwarn", "alias": [], "category": "grupo", "desc": "Quitar advertencia."},
    {"name": "link", "alias": ["/enlace"], "category": "grupo", "desc": "Link del grupo."},

    // --- 🧠 IA ---
    {"name": "ia", "alias": ["/chatgpt"], "category": "ia", "desc": "ChatGPT."},
    {"name": "dalle", "alias": ["/iaimg", "/aiimage"], "category": "ia", "desc": "Imagen IA."},
    {"name": "aigensfw", "alias": ["/nsfwaigen", "/pornogen"], "category": "ia", "desc": "IA +18."},

    // --- ℹ️ Información ---
    {"name": "menu", "alias": ["/help", "/menú"], "category": "info", "desc": "Ver comandos."},
    {"name": "infobot", "alias": ["/infosocket", "/status"], "category": "info", "desc": "Estado del bot."},
    {"name": "ping", "alias": ["/p"], "category": "info", "desc": "Velocidad."},
    {"name": "report", "alias": ["/reporte"], "category": "info", "desc": "Reportar error."},
    {"name": "suggest", "alias": ["/sug"], "category": "info", "desc": "Sugerencia."},
    {"name": "invite", "alias": ["/invitar"], "category": "info", "desc": "Invitar bot."},
    {"name": "owner", "alias": ["/creador", "/contacto"], "category": "info", "desc": "Dueño."},
    {"name": "hosting", "alias": [], "category": "info", "desc": "Info host."},

    // --- 🔞 NSFW (+18) ---
    {"name": "danbooru", "alias": ["/dbooru"], "category": "nsfw", "desc": "Danbooru."},
    {"name": "gelbooru", "alias": ["/gbooru"], "category": "nsfw", "desc": "Gelbooru."},
    {"name": "rule34", "alias": ["/r34"], "category": "nsfw", "desc": "Rule34."},
    {"name": "hentai", "alias": [], "category": "nsfw", "desc": "Hentai random."},
    {"name": "xVideos", "alias": ["/xnxx", "/xvideos"], "category": "nsfw", "desc": "Video XXX."},
    {"name": "anal", "alias": [], "category": "nsfw", "desc": "Anal."},
    {"name": "cum", "alias": ["/leche", "/venirse"], "category": "nsfw", "desc": "Cumshot."},
    {"name": "undress", "alias": ["/encuerar", "/desnudar"], "category": "nsfw", "desc": "Desnudar."},
    {"name": "fuck", "alias": ["/coger"], "category": "nsfw", "desc": "Follar."},
    {"name": "spank", "alias": ["/nalgada", "/azotar"], "category": "nsfw", "desc": "Nalgada."},
    {"name": "lickpussy", "alias": [], "category": "nsfw", "desc": "Lamer coño."},
    {"name": "fap", "alias": ["/paja", "/dedear", "/fingering"], "category": "nsfw", "desc": "Masturbación."},
    {"name": "grope", "alias": ["/manosear", "/toquetear"], "category": "nsfw", "desc": "Manosear."},
    {"name": "sixnine", "alias": ["/69"], "category": "nsfw", "desc": "69."},
    {"name": "suckboobs", "alias": ["/chupartetas"], "category": "nsfw", "desc": "Chupar tetas."},
    {"name": "grabboobs", "alias": ["/agarrartetas"], "category": "nsfw", "desc": "Agarrar tetas."},
    {"name": "blowjob", "alias": ["/bj", "/mamada"], "category": "nsfw", "desc": "Mamada."},
    {"name": "boobjob", "alias": ["/rusa"], "category": "nsfw", "desc": "Rusa."},
    {"name": "footjob", "alias": ["/pies"], "category": "nsfw", "desc": "Pies."},
    {"name": "hentaivid", "alias": ["/hentaivideo"], "category": "nsfw", "desc": "Video Hentai."},
    {"name": "yuri", "alias": ["/imagenlesbians"], "category": "nsfw", "desc": "Yuri/Lesbianas."},
    {"name": "pene", "alias": [], "category": "nsfw", "desc": "Pene."},
    {"name": "culo", "alias": [], "category": "nsfw", "desc": "Culo."},
    {"name": "tetas", "alias": [], "category": "nsfw", "desc": "Tetas."},
    {"name": "orgy", "alias": ["/orgia", "/trio", "/threesome", "/gangbang"], "category": "nsfw", "desc": "Orgía."},
    {"name": "bdsm", "alias": ["/bondage", "/amarrar", "/atar"], "category": "nsfw", "desc": "BDSM."},
    {"name": "ecchi", "alias": [], "category": "nsfw", "desc": "Ecchi."},
    {"name": "panties", "alias": [], "category": "nsfw", "desc": "Ropa interior."},
    {"name": "tentacle", "alias": ["/tentaculos"], "category": "nsfw", "desc": "Tentáculos."},
    {"name": "nsfwloli", "alias": [], "category": "nsfw", "desc": "Loli H (Bannable)."},
    {"name": "nsfwfoot", "alias": [], "category": "nsfw", "desc": "Pies H."},

    // --- 👤 Perfil ---
    {"name": "level", "alias": ["/lvl", "/levelup"], "category": "profile", "desc": "Nivel."},
    {"name": "marry", "alias": ["/casarse"], "category": "profile", "desc": "Casarse."},
    {"name": "divorce", "alias": ["/divorcio"], "category": "profile", "desc": "Divorciarse."},
    {"name": "profile", "alias": ["/perfil"], "category": "profile", "desc": "Ver perfil."},
    {"name": "setbirth", "alias": [], "category": "profile", "desc": "Poner cumpleaños."},
    {"name": "delbirth", "alias": [], "category": "profile", "desc": "Borrar cumpleaños."},
    {"name": "setdescription", "alias": ["/setdesc"], "category": "profile", "desc": "Poner descripción."},
    {"name": "deldescription", "alias": ["/deldesc"], "category": "profile", "desc": "Borrar descripción."},
    {"name": "setgenre", "alias": [], "category": "profile", "desc": "Poner género."},
    {"name": "delgenre", "alias": [], "category": "profile", "desc": "Borrar género."},
    {"name": "sethobby", "alias": ["/setpasatiempo"], "category": "profile", "desc": "Poner hobby."},
    {"name": "removehobby", "alias": ["/delpasatiempo"], "category": "profile", "desc": "Borrar hobby."},

    // --- 🤖 Sub-Bots (Sockets) ---
    {"name": "bots", "alias": ["/sockets"], "category": "sockets", "desc": "Lista sub-bots."},
    {"name": "logout", "alias": ["/logout2", "/clearsubs"], "category": "sockets", "desc": "Cerrar sesión."},
    {"name": "qr", "alias": ["/code"], "category": "sockets", "desc": "QR Sub-bot."},
    {"name": "qrpremium", "alias": ["/codepremium"], "category": "sockets", "desc": "QR Premium."},
    {"name": "qrmod", "alias": ["/codemod"], "category": "sockets", "desc": "QR Mod."},
    {"name": "self", "alias": [], "category": "sockets", "desc": "Modo privado."},
    {"name": "set", "alias": ["/edit"], "category": "sockets", "desc": "Editar bot."},
    {"name": "leave", "alias": [], "category": "sockets", "desc": "Salir del grupo."},
    {"name": "setname", "alias": ["/setbotname"], "category": "sockets", "desc": "Nombre bot."},
    {"name": "setprefix", "alias": ["/setbotprefix"], "category": "sockets", "desc": "Prefijo bot."},
    {"name": "seticon", "alias": ["/setpfp"], "category": "sockets", "desc": "Icono bot."},
    {"name": "setbio", "alias": ["/setstatus"], "category": "sockets", "desc": "Bio bot."},

    // --- 🛠️ Utilidades ---
    {"name": "sticker", "alias": ["/s"], "category": "utils", "desc": "Sticker."},
    {"name": "getpic", "alias": ["/pfp"], "category": "utils", "desc": "Foto perfil."},
    {"name": "tourl", "alias": ["/upload"], "category": "utils", "desc": "Subir a URL."},
    {"name": "translate", "alias": ["/tr"], "category": "utils", "desc": "Traducir."},
    {"name": "get", "alias": [], "category": "utils", "desc": "Petición GET."},
    {"name": "setmeta", "alias": [], "category": "utils", "desc": "Metadata sticker."},
    {"name": "hd", "alias": ["/upscale"], "category": "utils", "desc": "Mejorar calidad."},
    {"name": "rvocal", "alias": [], "category": "utils", "desc": "Quitar voz."},
    {"name": "wm", "alias": [], "category": "utils", "desc": "Marca de agua."},
    {"name": "confesión", "alias": ["/confesar"], "category": "utils", "desc": "Confesión."},
    {"name": "responder", "alias": [], "category": "utils", "desc": "Responder confesión."},
    {"name": "setalias", "alias": [], "category": "utils", "desc": "Alias usuario."},
    {"name": "delalias", "alias": [], "category": "utils", "desc": "Borrar alias."},
    {"name": "tofigure", "alias": ["/tf"], "category": "utils", "desc": "A figura."},
    {"name": "qc", "alias": [], "category": "utils", "desc": "Sticker texto."},

    // --- 🌀 Juegos ---
    {"name": "ahorcado", "alias": ["/hangman"], "category": "rpg", "desc": "Ahorcado."},

    // --- 🌀 Otros (Scripts sueltos) ---
    {"name": "eval", "alias": ["/=>"], "category": "otros", "desc": "Evaluar código."},
    {"name": "exec", "alias": ["/$"], "category": "otros", "desc": "Terminal."},
    {"name": "restart", "alias": ["/update"], "category": "otros", "desc": "Reiniciar."},
    {"name": "fix", "alias": ["/clean"], "category": "otros", "desc": "Limpiar sesión."}
]
