export const commands = [
    // --- 🎬 Anime Reacciones (PurrBot v1 + Nekos.best - 80 comandos animados) ---
    {"name": "kiss", "alias": ["besar"], "category": "anime", "desc": "Besar a alguien."},
    {"name": "hug", "alias": ["abrazar"], "category": "anime", "desc": "Abrazar."},
    {"name": "pat", "alias": ["acariciar"], "category": "anime", "desc": "Acariciar."},
    {"name": "poke", "alias": ["picar"], "category": "anime", "desc": "Picar."},
    {"name": "slap", "alias": ["bofetada"], "category": "anime", "desc": "Abofetear."},
    {"name": "bite", "alias": ["morder"], "category": "anime", "desc": "Morder."},
    {"name": "punch", "alias": ["golpear"], "category": "anime", "desc": "Golpear."},
    {"name": "kickanime", "alias": ["patada", "patear"], "category": "anime", "desc": "Patada (anime)."},
    {"name": "kill", "alias": ["matar", "decapitar"], "category": "anime", "desc": "Matar."},
    {"name": "cuddle", "alias": ["acurrucar"], "category": "anime", "desc": "Acurrucarse."},
    {"name": "dance", "alias": ["bailar"], "category": "anime", "desc": "Bailar."},
    {"name": "run", "alias": ["correr"], "category": "anime", "desc": "Correr."},
    {"name": "wave", "alias": ["saludar"], "category": "anime", "desc": "Saludar."},
    {"name": "smile", "alias": ["sonreir"], "category": "anime", "desc": "Sonreír."},
    {"name": "wink", "alias": ["guiñar"], "category": "anime", "desc": "Guiñar ojo."},
    {"name": "blush", "alias": ["sonrojarse"], "category": "anime", "desc": "Sonrojarse."},
    {"name": "cry", "alias": ["llorar"], "category": "anime", "desc": "Llorar."},
    {"name": "eat", "alias": ["comer"], "category": "anime", "desc": "Comer."},
    {"name": "tickle", "alias": ["cosquillas"], "category": "anime", "desc": "Hacerle cosquillas."},
    {"name": "feed", "alias": ["alimentar"], "category": "anime", "desc": "Alimentar."},
    {"name": "meow", "alias": ["maullar"], "category": "anime", "desc": "Maullar como gato."},
    {"name": "neko", "alias": [], "category": "anime", "desc": "Ser un neko."},
    {"name": "lizard", "alias": [], "category": "anime", "desc": "Ser un lagarto."},
    {"name": "woof", "alias": ["guau"], "category": "anime", "desc": "Ladrar."},
    {"name": "fox_girl", "alias": ["chicazorro"], "category": "anime", "desc": "Chica zorro."},
    {"name": "smug", "alias": [], "category": "anime", "desc": "Sonrisa altiva."},
    {"name": "lewd", "alias": [], "category": "anime", "desc": "Provocador."},
    {"name": "spank", "alias": ["nalgada"], "category": "anime", "desc": "Nalgada."},
    {"name": "gasm", "alias": ["jadear"], "category": "anime", "desc": "Jadear apasionadamente."},
    {"name": "gecko", "alias": [], "category": "anime", "desc": "Ser un gecko."},
    {"name": "angry", "alias": ["enojado", "furioso"], "category": "anime", "desc": "Enojarse."},
    {"name": "fluff", "alias": ["esponjoso"], "category": "anime", "desc": "Reacción fluffy."},
    {"name": "lick", "alias": ["lamer"], "category": "anime", "desc": "Lamer."},
    {"name": "pout", "alias": ["puchero"], "category": "anime", "desc": "Hacer puchero."},
    {"name": "tail", "alias": ["cola"], "category": "anime", "desc": "Mover la cola."},
    {"name": "comfy", "alias": ["comodo"], "category": "anime", "desc": "Estar cómodo."},
    {"name": "highfive", "alias": ["choquepalmas"], "category": "anime", "desc": "Chocar los cinco."},
    {"name": "handhold", "alias": ["tomarmano"], "category": "anime", "desc": "Tomar de la mano."},
    {"name": "nom", "alias": [], "category": "anime", "desc": "Nom nom."},
    {"name": "laugh", "alias": ["reir"], "category": "anime", "desc": "Reír."},
    {"name": "yeet", "alias": ["lanzar"], "category": "anime", "desc": "Lanzar."},
    {"name": "shrug", "alias": ["encoger"], "category": "anime", "desc": "Encogerse de hombros."},
    {"name": "stare", "alias": ["mirar"], "category": "anime", "desc": "Mirada fija."},
    {"name": "think", "alias": ["pensar"], "category": "anime", "desc": "Pensar."},
    {"name": "peck", "alias": ["besito"], "category": "anime", "desc": "Dar un besito."},
    {"name": "cheekkiss", "alias": ["besomejilla", "besodemejilla"], "category": "anime", "desc": "Beso de mejilla."},
    {"name": "embarazo", "alias": ["embarazar", "preñar"], "category": "anime", "desc": "Embarazo estilo anime."},
    {"name": "bite_head", "alias": ["morderescarabajo"], "category": "anime", "desc": "Morder cabeza."},
    {"name": "bleh", "alias": ["burla"], "category": "anime", "desc": "Sacar la lengua."},
    {"name": "bonk", "alias": ["golpecito"], "category": "anime", "desc": "Golpecito en la cabeza."},
    {"name": "bored", "alias": ["aburrido"], "category": "anime", "desc": "Estar aburrido."},
    {"name": "bully", "alias": ["acosar"], "category": "anime", "desc": "Acosar."},
    {"name": "celebrate", "alias": ["celebrar"], "category": "anime", "desc": "Celebrar."},
    {"name": "clap", "alias": ["aplaudir"], "category": "anime", "desc": "Aplaudir."},
    {"name": "coffee", "alias": ["cafe"], "category": "anime", "desc": "Tomar café."},
    {"name": "comfort", "alias": ["consolar"], "category": "anime", "desc": "Consolar."},
    {"name": "confused", "alias": ["confundido"], "category": "anime", "desc": "Estar confundido."},
    {"name": "cringe", "alias": ["vergüenza"], "category": "anime", "desc": "Avergonzarse."},
    {"name": "dramatic", "alias": ["dramatico"], "category": "anime", "desc": "Modo dramático."},
    {"name": "drunk", "alias": ["borracho"], "category": "anime", "desc": "Estar borracho."},
    {"name": "flick", "alias": ["flequillo"], "category": "anime", "desc": "Movimiento de flequillo."},
    {"name": "freeze", "alias": ["congelar"], "category": "anime", "desc": "Congelarse."},
    {"name": "grab", "alias": ["agarrar"], "category": "anime", "desc": "Agarrar."},
    {"name": "happy", "alias": ["feliz"], "category": "anime", "desc": "Estar feliz."},
    {"name": "impregnate", "alias": ["embarazar"], "category": "anime", "desc": "Embarazar."},
    {"name": "knead", "alias": ["amasar"], "category": "anime", "desc": "Amasar."},
    {"name": "love", "alias": ["amar"], "category": "anime", "desc": "Estar enamorado."},
    {"name": "sad", "alias": ["triste"], "category": "anime", "desc": "Estar triste."},
    {"name": "scared", "alias": ["asustado"], "category": "anime", "desc": "Estar asustado."},
    {"name": "seduce", "alias": ["seducir"], "category": "anime", "desc": "Seducir."},
    {"name": "shock", "alias": ["shock"], "category": "anime", "desc": "Shock."},
    {"name": "shy", "alias": ["timido"], "category": "anime", "desc": "Estar tímido."},
    {"name": "sing", "alias": ["cantar"], "category": "anime", "desc": "Cantar."},
    {"name": "sleep", "alias": ["dormir"], "category": "anime", "desc": "Dormir."},
    {"name": "slurp", "alias": ["sorber"], "category": "anime", "desc": "Sorber."},
    {"name": "smoke", "alias": ["fumar"], "category": "anime", "desc": "Fumar."},
    {"name": "spit", "alias": ["escupir"], "category": "anime", "desc": "Escupir."},
    {"name": "splash", "alias": ["salpicar"], "category": "anime", "desc": "Salpicar agua."},
    {"name": "trip", "alias": ["tropezar"], "category": "anime", "desc": "Tropezar."},
    {"name": "walk", "alias": ["caminar"], "category": "anime", "desc": "Caminar."},
    {"name": "peek", "alias": ["mirar_escondidas"], "category": "anime", "desc": "Mirar escondidas."},

    // --- 🔎 Búsquedas ---
    {"name": "pinterest", "alias": ["pin"], "category": "search", "desc": "Buscar Pinterest."},
    {"name": "imagen", "alias": ["img", "image"], "category": "search", "desc": "Buscar Google."},
    {"name": "aptoide", "alias": ["apk", "apkdl"], "category": "search", "desc": "Apps Aptoide."},
    {"name": "ytsearch", "alias": ["yts"], "category": "search", "desc": "Buscar YouTube."},
    {"name": "tiktoksearch", "alias": ["ttsearch", "tsearch"], "category": "search", "desc": "Buscar TikTok."},
    {"name": "tts", "alias": ["texttospeech"], "category": "search", "desc": "Texto a voz."},

    // --- 📥 Descargas ---
    {"name": "facebook", "alias": ["fb"], "category": "download", "desc": "Descargar FB."},
    {"name": "instagram", "alias": ["ig", "igdl", "instadl"], "category": "download", "desc": "Descargar IG."},
    {"name": "tiktok", "alias": ["tt", "tiktokdl", "ttdl"], "category": "download", "desc": "Descargar TT."},
    {"name": "play", "alias": ["play2", "mp3", "mp4", "ytmp3", "ytmp4"], "category": "download", "desc": "Descargar YT."},
    {"name": "song", "alias": ["yta", "ytaudio", "video", "ytv", "ytvideo"], "category": "download", "desc": "Audio/Video directo de YT."},
    {"name": "spotify", "alias": ["spot"], "category": "download", "desc": "Descargar Spotify."},
    {"name": "mediafire", "alias": ["mf"], "category": "download", "desc": "Mediafire."},
    {"name": "mega", "alias": ["mg"], "category": "download", "desc": "Mega."},
    {"name": "modapk", "alias": ["apkmod"], "category": "download", "desc": "APK Mod."},
    {"name": "twitter", "alias": ["x", "xtt", "xtwitter"], "category": "download", "desc": "Twitter/X."},
    {"name": "gitclone", "alias": ["git"], "category": "download", "desc": "Git Clone."},
    {"name": "drive", "alias": ["gdrive"], "category": "download", "desc": "Google Drive."},

    // --- 💰 Economía ---
    {"name": "balance", "alias": ["bal"], "category": "economia", "desc": "Ver dinero."},
    {"name": "steal", "alias": ["rob", "robar"], "category": "economia", "desc": "Robar dinero."},
    {"name": "crime", "alias": ["crimen"], "category": "economia", "desc": "Cometer crimen."},
    {"name": "givecoins", "alias": ["pay", "coinsgive", "darplata", "transfer"], "category": "economia", "desc": "Transferir."},
    {"name": "ppt", "alias": ["piedrapapeltijera"], "category": "economia", "desc": "Piedra Papel Tijera."},
    {"name": "math", "alias": ["matematicas"], "category": "economia", "desc": "Resolver mates."},
    {"name": "waittimes", "alias": ["cooldowns", "einfo", "economyinfo"], "category": "economia", "desc": "Ver tiempos."},
    {"name": "economyboard", "alias": ["baltop", "eboard"], "category": "economia", "desc": "Top Ricos."},
    {"name": "slut", "alias": [], "category": "economia", "desc": "Trabajo +18."},
    {"name": "mine", "alias": ["minar"], "category": "economia", "desc": "Minar."},
    {"name": "rt", "alias": ["roulette", "ruleta"], "category": "economia", "desc": "Ruleta."},
    {"name": "coinflip", "alias": ["flip", "cf"], "category": "economia", "desc": "Cara o Cruz."},
    {"name": "daily", "alias": ["diario"], "category": "economia", "desc": "Diario."},
    {"name": "monthly", "alias": ["mensual"], "category": "economia", "desc": "Mensual."},
    {"name": "weekly", "alias": ["semanal"], "category": "economia", "desc": "Semanal."},
    {"name": "work", "alias": ["w", "trabajar"], "category": "economia", "desc": "Trabajar."},
    {"name": "deposit", "alias": ["dep", "d"], "category": "economia", "desc": "Depositar."},
    {"name": "withdraw", "alias": ["with", "retirar"], "category": "economia", "desc": "Retirar."},
    {"name": "logros", "alias": [], "category": "economia", "desc": "Ver logros."},
    {"name": "toplogros", "alias": [], "category": "economia", "desc": "Top logros."},
    {"name": "evento", "alias": ["event", "eventdiario"], "category": "economia", "desc": "Evento diario."},
    {"name": "eventos", "alias": ["events"], "category": "economia", "desc": "Ver eventos activos."},
    {"name": "eventsemanal", "alias": [], "category": "economia", "desc": "Evento semanal."},
    {"name": "drop", "alias": ["recoger", "atrapar", "grab"], "category": "economia", "desc": "Recoger drop aleatorio."},
    {"name": "fish", "alias": ["pescar", "pesca", "fishing"], "category": "economia", "desc": "Pescar peces."},
    {"name": "slots", "alias": ["tragamonedas", "slot"], "category": "economia", "desc": "Tragamonedas."},
    {"name": "duel", "alias": ["duelo", "pelea", "fight"], "category": "economia", "desc": "Duelar por monedas."},
    {"name": "explore", "alias": ["explorar", "aventura", "adventure"], "category": "economia", "desc": "Explorar zonas."},
    {"name": "lottery", "alias": ["loteria", "loto", "boleto"], "category": "economia", "desc": "Lotería."},

    // --- � RPG Sistema de XP ---
    {"name": "skills", "alias": ["habilidades", "skilltree", "arbol"], "category": "rpg", "desc": "Árbol de habilidades."},
    {"name": "class", "alias": ["clase", "classes", "clases"], "category": "rpg", "desc": "Sistema de clases."},
    {"name": "arena", "alias": ["battle", "batalla", "pelear", "boss"], "category": "rpg", "desc": "Arena PvE."},
    {"name": "prestige", "alias": ["prestigio", "rebirth", "renacer"], "category": "rpg", "desc": "Prestige / Renacer."},
    {"name": "missions", "alias": ["misiones", "mission", "mision", "quests"], "category": "rpg", "desc": "Misiones diarias."},

    // --- �🎲 Gacha ---
    {"name": "rw", "alias": ["roll", "rollwaifu", "rf"], "category": "gacha", "desc": "Girar waifu."},
    {"name": "c", "alias": ["claim", "buy"], "category": "gacha", "desc": "Reclamar waifu."},
    {"name": "harem", "alias": ["miswaifus", "claims"], "category": "gacha", "desc": "Colección."},
    {"name": "sell", "alias": ["vender", "removesale"], "category": "gacha", "desc": "Vender waifu."},
    {"name": "buyc", "alias": ["buycharacter", "buychar"], "category": "gacha", "desc": "Comprar waifu."},
    {"name": "trade", "alias": ["cambiar"], "category": "gacha", "desc": "Intercambiar."},
    {"name": "animelist", "alias": ["slist", "serielist"], "category": "gacha", "desc": "Lista series."},
    {"name": "animeinfo", "alias": ["ainfo", "serieinfo"], "category": "gacha", "desc": "Info anime."},
    {"name": "tiendawaifus", "alias": ["wshop", "haremshop"], "category": "gacha", "desc": "Tienda."},
    {"name": "delrw", "alias": ["delwaifu", "delp"], "category": "gacha", "desc": "Borrar waifu."},
    {"name": "removerventa", "alias": ["retirarventa"], "category": "gacha", "desc": "Quitar venta."},
    {"name": "darrw", "alias": ["givewaifu", "givechar"], "category": "gacha", "desc": "Regalar waifu."},
    {"name": "giveallharem", "alias": [], "category": "gacha", "desc": "Regalar todo."},
    {"name": "ginfo", "alias": ["infogacha", "gachainfo"], "category": "gacha", "desc": "Info gacha."},
    {"name": "verpersonaje", "alias": ["vp"], "category": "gacha", "desc": "Ver personaje."},
    {"name": "character", "alias": ["charinfo", "cinfo"], "category": "gacha", "desc": "Info carta."},
    {"name": "vote", "alias": ["votar"], "category": "gacha", "desc": "Votar waifu."},
    {"name": "accepttrade", "alias": ["aceptarintercambio"], "category": "gacha", "desc": "Aceptar cambio."},
    {"name": "waifusboard", "alias": ["waifustop", "toprw"], "category": "gacha", "desc": "Top Gacha."},
    {"name": "votesboard", "alias": ["topvotos", "topwaifus"], "category": "gacha", "desc": "Top Votos."},
    {"name": "wimage", "alias": ["charimage", "cimage"], "category": "gacha", "desc": "Imagen Carta."},
    {"name": "robarwaifu", "alias": ["robarwaifu", "stealwaifu", "stealchar"], "category": "gacha", "desc": "Robar waifu"},

    // --- 👥 Grupo ---
    {"name": "mute", "alias": ["silenciar"], "category": "grupo", "desc": "Silenciar bot."},
    {"name": "promote", "alias": ["admin", "daradmin"], "category": "grupo", "desc": "Dar admin."},
    {"name": "demote", "alias": ["quitaradmin"], "category": "grupo", "desc": "Quitar admin."},
    {"name": "transfer", "alias": [], "category": "grupo", "desc": "Transferir propiedad."},
    {"name": "setprimary", "alias": [], "category": "grupo", "desc": "Bot primario."},
    {"name": "setgpbaner", "alias": ["setgpbanner"], "category": "grupo", "desc": "Foto grupo."},
    {"name": "setgpname", "alias": ["setname"], "category": "grupo", "desc": "Nombre grupo."},
    {"name": "setgpdesc", "alias": [], "category": "grupo", "desc": "Desc grupo."},
    {"name": "closet", "alias": ["cerrar"], "category": "grupo", "desc": "Cerrar grupo."},
    {"name": "open", "alias": ["abrir"], "category": "grupo", "desc": "Abrir grupo."},
    {"name": "delete", "alias": ["del"], "category": "grupo", "desc": "Borrar mensaje."},
    {"name": "audios", "alias": [], "category": "grupo", "desc": "Auto-audios (ej: audios add hola,buenas)."},
    {"name": "on", "alias": ["welcome", "antilink", "nsfw", "rpg", "economia"], "category": "grupo", "desc": "Activar."},
    {"name": "off", "alias": [], "category": "grupo", "desc": "Desactivar."},
    {"name": "groupinfo", "alias": ["gp", "infogrupo"], "category": "grupo", "desc": "Info grupo."},
    {"name": "tag", "alias": ["hidetag", "notificar"], "category": "grupo", "desc": "Mencionar todos."},
    {"name": "kick", "alias": ["ban", "echar"], "category": "grupo", "desc": "Expulsar."},
    {"name": "warn", "alias": ["advertir", "warns"], "category": "grupo", "desc": "Advertencias."},
    {"name": "delwarn", "alias": [], "category": "grupo", "desc": "Quitar advertencia."},
    {"name": "link", "alias": ["enlace"], "category": "grupo", "desc": "Link grupo."},

    // --- 🧠 IA ---
    {"name": "ia", "alias": ["chatgpt", "gpt", "lucoa"], "category": "ia", "desc": "Chat con Lucoa."},
    {"name": "dalle", "alias": ["iaimg", "aiimage", "genimg"], "category": "ia", "desc": "Imagen IA."},
    {"name": "aigensfw", "alias": ["nsfwaigen", "pornogen", "ainsfw"], "category": "ia", "desc": "Imagen IA +18."},

    // --- ℹ️ Información ---
    {"name": "menu", "alias": ["help", "comandos", "menú"], "category": "info", "desc": "Ver menú."},
    {"name": "infobot", "alias": ["infosocket", "status"], "category": "info", "desc": "Estado bot."},
    {"name": "ping", "alias": ["p", "velocidad"], "category": "info", "desc": "Ver ping."},
    {"name": "report", "alias": ["reporte"], "category": "info", "desc": "Reportar error."},
    {"name": "suggest", "alias": ["sug"], "category": "info", "desc": "Sugerencia."},
    {"name": "invite", "alias": ["invitar"], "category": "info", "desc": "Invitar bot."},
    {"name": "owner", "alias": ["creador", "contacto", "cafi", "cafirexos"], "category": "info", "desc": "Dueño."},
    {"name": "hosting", "alias": [], "category": "info", "desc": "Info hosting."},

    // --- 🔞 NSFW (+18) ---
    {"name": "danbooru", "alias": ["dbooru"], "category": "nsfw", "desc": "Danbooru."},
    {"name": "gelbooru", "alias": ["gbooru"], "category": "nsfw", "desc": "Gelbooru."},
    {"name": "rule34", "alias": ["r34"], "category": "nsfw", "desc": "Rule34."},
    {"name": "hentai", "alias": [], "category": "nsfw", "desc": "Imagen Hentai."},
    {"name": "xVideos", "alias": ["xnxx", "xvideos"], "category": "nsfw", "desc": "Videos XXX."},
    {"name": "anal", "alias": [], "category": "nsfw", "desc": "Anal."},
    {"name": "cum", "alias": ["leche", "venirse"], "category": "nsfw", "desc": "Cumshot."},
    {"name": "undress", "alias": ["encuerar", "desnudar"], "category": "nsfw", "desc": "Desnudar."},
    {"name": "fuck", "alias": ["coger", "follar"], "category": "nsfw", "desc": "Follar."},
    {"name": "spank", "alias": ["nalgada", "azotar"], "category": "nsfw", "desc": "Nalgada."},
    {"name": "lickpussy", "alias": ["lamercoño"], "category": "nsfw", "desc": "Lamer."},
    {"name": "fap", "alias": ["paja", "dedear", "fingering"], "category": "nsfw", "desc": "Masturbación."},
    {"name": "grope", "alias": ["manosear", "toquetear"], "category": "nsfw", "desc": "Manosear."},
    {"name": "sixnine", "alias": ["69"], "category": "nsfw", "desc": "69."},
    {"name": "suckboobs", "alias": ["chupartetas"], "category": "nsfw", "desc": "Chupar tetas."},
    {"name": "grabboobs", "alias": ["agarrartetas"], "category": "nsfw", "desc": "Agarrar tetas."},
    {"name": "blowjob", "alias": ["bj", "mamada"], "category": "nsfw", "desc": "Mamada."},
    {"name": "boobjob", "alias": ["rusa"], "category": "nsfw", "desc": "Rusa."},
    {"name": "footjob", "alias": ["pies"], "category": "nsfw", "desc": "Pies."},
    {"name": "hentaivid", "alias": ["hentaivideo"], "category": "nsfw", "desc": "Video Hentai."},
    {"name": "yuri", "alias": ["imagenlesbians"], "category": "nsfw", "desc": "Yuri."},
    {"name": "neko18", "alias": ["gatita", "nekita"], "category": "nsfw", "desc": "Modo neko."},
    {"name": "solo", "alias": ["autosolo", "solito"], "category": "nsfw", "desc": "Modo solo."},
    {"name": "pene", "alias": [], "category": "nsfw", "desc": "Pene."},
    {"name": "culo", "alias": [], "category": "nsfw", "desc": "Culo."},
    {"name": "tetas", "alias": [], "category": "nsfw", "desc": "Tetas."},
    {"name": "orgy", "alias": ["orgia", "trio", "threesome", "gangbang"], "category": "nsfw", "desc": "Orgía."},
    {"name": "bdsm", "alias": ["bondage", "amarrar", "atar"], "category": "nsfw", "desc": "BDSM."},
    {"name": "ecchi", "alias": [], "category": "nsfw", "desc": "Ecchi."},
    {"name": "panties", "alias": ["ropainterior"], "category": "nsfw", "desc": "Ropa interior."},
    {"name": "tentacle", "alias": ["tentaculos"], "category": "nsfw", "desc": "Tentáculos."},
    {"name": "nsfwloli", "alias": [], "category": "nsfw", "desc": "Loli H."},
    {"name": "nsfwfoot", "alias": [], "category": "nsfw", "desc": "Pies H."},

    // --- 👤 Perfil ---
    {"name": "level", "alias": ["lvl", "levelup"], "category": "profile", "desc": "Nivel."},
    {"name": "marry", "alias": ["casarse"], "category": "profile", "desc": "Casarse."},
    {"name": "divorce", "alias": ["divorcio"], "category": "profile", "desc": "Divorciarse."},
    {"name": "profile", "alias": ["perfil"], "category": "profile", "desc": "Ver perfil."},
    {"name": "setbirth", "alias": [], "category": "profile", "desc": "Poner cumple."},
    {"name": "delbirth", "alias": [], "category": "profile", "desc": "Borrar cumple."},
    {"name": "setdescription", "alias": ["setdesc", "setbio"], "category": "profile", "desc": "Poner bio."},
    {"name": "deldescription", "alias": ["deldesc"], "category": "profile", "desc": "Borrar bio."},
    {"name": "setgenre", "alias": [], "category": "profile", "desc": "Poner género."},
    {"name": "delgenre", "alias": [], "category": "profile", "desc": "Borrar género."},
    {"name": "sethobby", "alias": ["setpasatiempo"], "category": "profile", "desc": "Poner hobby."},
    {"name": "removehobby", "alias": ["delpasatiempo"], "category": "profile", "desc": "Borrar hobby."},

    // --- 🤖 Sub-Bots ---
    {"name": "bots", "alias": ["sockets"], "category": "sockets", "desc": "Lista bots."},
    {"name": "logout", "alias": ["logout2", "clearsubs", "stop"], "category": "sockets", "desc": "Apagar bot."},
    {"name": "qr", "alias": ["code", "jadibot"], "category": "sockets", "desc": "Ser bot (QR)."},
    {"name": "qrpremium", "alias": ["codepremium"], "category": "sockets", "desc": "QR Premium."},
    {"name": "qrmod", "alias": ["codemod"], "category": "sockets", "desc": "QR Mod."},
    {"name": "self", "alias": [], "category": "sockets", "desc": "Modo privado."},
    {"name": "set", "alias": ["edit"], "category": "sockets", "desc": "Editar bot."},
    {"name": "leave", "alias": [], "category": "sockets", "desc": "Salir grupo."},
    {"name": "setname", "alias": ["setbotname"], "category": "sockets", "desc": "Nombre bot."},
    {"name": "setprefix", "alias": ["setbotprefix"], "category": "sockets", "desc": "Prefijo bot."},
    {"name": "seticon", "alias": ["setpfp"], "category": "sockets", "desc": "Icono bot."},
    {"name": "setbio", "alias": ["setstatus"], "category": "sockets", "desc": "Bio bot."},

    // --- 🛠️ Utilidades ---
    {"name": "sticker", "alias": ["s"], "category": "utils", "desc": "Sticker."},
    {"name": "getpic", "alias": ["pfp"], "category": "utils", "desc": "Foto perfil."},
    {"name": "tourl", "alias": ["upload"], "category": "utils", "desc": "Subir URL."},
    {"name": "translate", "alias": ["tr"], "category": "utils", "desc": "Traducir."},
    {"name": "get", "alias": [], "category": "utils", "desc": "Ver código."},
    {"name": "setmeta", "alias": [], "category": "utils", "desc": "Meta sticker."},
    {"name": "hd", "alias": ["upscale"], "category": "utils", "desc": "Mejorar calidad."},
    {"name": "rvocal", "alias": [], "category": "utils", "desc": "Quitar voz."},
    {"name": "wm", "alias": [], "category": "utils", "desc": "Marca de agua."},
    {"name": "confesión", "alias": ["confesar"], "category": "utils", "desc": "Confesión."},
    {"name": "responder", "alias": [], "category": "utils", "desc": "Responder."},
    {"name": "setalias", "alias": [], "category": "utils", "desc": "Alias usuario."},
    {"name": "delalias", "alias": [], "category": "utils", "desc": "Borrar alias."},
    {"name": "tofigure", "alias": ["tf"], "category": "utils", "desc": "Sticker silueta."},
    {"name": "toimage", "alias": [], "category": "utils", "desc": "Sticker a imagen."},
    {"name": "qc", "alias": [], "category": "utils", "desc": "Sticker texto."},
    
    // --- 🌀 RPG / Juegos ---
    {"name": "ahorcado", "alias": ["hangman"], "category": "rpg", "desc": "Ahorcado."},

    // --- 🌀 Otros (Propietario / Admins) ---
    {"name": "resetuser", "alias": ["restablecerdatos", "deletedatauser"], "category": "otros", "desc": "Borrar base usuario."},
    {"name": "antiestado", "alias": ["antistatus"], "category": "grupo", "desc": "Control de menciones de estado."},
    {"name": "eval", "alias": ["=>"], "category": "otros", "desc": "Evaluar JS."},
    {"name": "exec", "alias": ["$"], "category": "otros", "desc": "Terminal."},
    {"name": "restart", "alias": ["update"], "category": "otros", "desc": "Reiniciar."},
    {"name": "fix", "alias": ["clean"], "category": "otros", "desc": "Limpiar sesión."}
]
