export const commands = [
    // --- 🌸 Anime & Reacciones (Lista Completa) ---
    {"name": "angry", "alias": [], "category": "anime", "desc": "Estar molesto."},
    {"name": "bleh", "alias": [], "category": "anime", "desc": "Sacar lengua."},
    {"name": "bored", "alias": [], "category": "anime", "desc": "Aburrido."},
    {"name": "kiss", "alias": ["besar"], "category": "anime", "desc": "Besar a alguien."},
    {"name": "clap", "alias": [], "category": "anime", "desc": "Aplaudir."},
    {"name": "coffee", "alias": [], "category": "anime", "desc": "Tomar café."},
    {"name": "dramatic", "alias": [], "category": "anime", "desc": "Dramático."},
    {"name": "drunk", "alias": [], "category": "anime", "desc": "Borracho."},
    {"name": "impregnate", "alias": ["embarazar"], "category": "anime", "desc": "Embarazar."},
    {"name": "laugh", "alias": ["reir", "jaja"], "category": "anime", "desc": "Reírse."},
    {"name": "love", "alias": ["amor"], "category": "anime", "desc": "Enamorarse."},
    {"name": "pout", "alias": ["puchero"], "category": "anime", "desc": "Hacer pucheros."},
    {"name": "punch", "alias": ["golpear"], "category": "anime", "desc": "Golpear."},
    {"name": "run", "alias": ["correr"], "category": "anime", "desc": "Correr."},
    {"name": "sad", "alias": ["triste"], "category": "anime", "desc": "Estar triste."},
    {"name": "scared", "alias": ["miedo"], "category": "anime", "desc": "Tener miedo."},
    {"name": "seduce", "alias": ["seducir"], "category": "anime", "desc": "Seducir."},
    {"name": "shy", "alias": ["timido"], "category": "anime", "desc": "Tímido."},
    {"name": "sleep", "alias": ["dormir"], "category": "anime", "desc": "Dormir."},
    {"name": "smoke", "alias": ["fumar"], "category": "anime", "desc": "Fumar."},
    {"name": "spit", "alias": ["escupir"], "category": "anime", "desc": "Escupir."},
    {"name": "step", "alias": ["pisar"], "category": "anime", "desc": "Pisar."},
    {"name": "think", "alias": ["pensar"], "category": "anime", "desc": "Pensar."},
    {"name": "walk", "alias": ["caminar"], "category": "anime", "desc": "Caminar."},
    {"name": "hug", "alias": ["abrazar"], "category": "anime", "desc": "Abrazar."},
    {"name": "kill", "alias": ["matar"], "category": "anime", "desc": "Matar."},
    {"name": "eat", "alias": ["comer"], "category": "anime", "desc": "Comer."},
    {"name": "wink", "alias": ["guiñar"], "category": "anime", "desc": "Guiñar ojo."},
    {"name": "pat", "alias": ["acariciar"], "category": "anime", "desc": "Acariciar."},
    {"name": "happy", "alias": ["feliz"], "category": "anime", "desc": "Feliz."},
    {"name": "bully", "alias": [], "category": "anime", "desc": "Hacer bullying."},
    {"name": "bite", "alias": ["morder"], "category": "anime", "desc": "Morder."},
    {"name": "blush", "alias": ["sonrojarse"], "category": "anime", "desc": "Sonrojarse."},
    {"name": "wave", "alias": ["saludar"], "category": "anime", "desc": "Saludar."},
    {"name": "bath", "alias": ["bañarse"], "category": "anime", "desc": "Bañarse."},
    {"name": "smug", "alias": ["presumir"], "category": "anime", "desc": "Presumir."},
    {"name": "smile", "alias": ["sonreir"], "category": "anime", "desc": "Sonreír."},
    {"name": "highfive", "alias": ["chocalas"], "category": "anime", "desc": "Chocar los cinco."},
    {"name": "handhold", "alias": ["mano"], "category": "anime", "desc": "Tomar la mano."},
    {"name": "cringe", "alias": [], "category": "anime", "desc": "Vergüenza ajena."},
    {"name": "bonk", "alias": [], "category": "anime", "desc": "Golpear cabeza."},
    {"name": "cry", "alias": ["llorar"], "category": "anime", "desc": "Llorar."},
    {"name": "lick", "alias": ["lamer"], "category": "anime", "desc": "Lamer."},
    {"name": "slap", "alias": ["bofetada"], "category": "anime", "desc": "Abofetear."},
    {"name": "dance", "alias": ["bailar"], "category": "anime", "desc": "Bailar."},
    {"name": "cuddle", "alias": ["acurrucarse"], "category": "anime", "desc": "Acurrucarse."},
    {"name": "cold", "alias": ["frio"], "category": "anime", "desc": "Tener frío."},
    {"name": "sing", "alias": ["cantar"], "category": "anime", "desc": "Cantar."},
    {"name": "tickle", "alias": ["cosquillas"], "category": "anime", "desc": "Cosquillas."},
    {"name": "scream", "alias": ["gritar"], "category": "anime", "desc": "Gritar."},
    {"name": "push", "alias": ["empujar"], "category": "anime", "desc": "Empujar."},
    {"name": "nope", "alias": ["negar"], "category": "anime", "desc": "Negar."},
    {"name": "jump", "alias": ["saltar"], "category": "anime", "desc": "Saltar."},
    {"name": "heat", "alias": ["calor"], "category": "anime", "desc": "Tener calor."},
    {"name": "gaming", "alias": ["jugar"], "category": "anime", "desc": "Jugar."},
    {"name": "draw", "alias": ["dibujar"], "category": "anime", "desc": "Dibujar."},
    {"name": "call", "alias": ["llamar"], "category": "anime", "desc": "Llamar."},
    {"name": "snuggle", "alias": [], "category": "anime", "desc": "Acurrucarse."},
    {"name": "blowkiss", "alias": ["lanzarbeso"], "category": "anime", "desc": "Lanzar beso."},
    {"name": "trip", "alias": ["tropezar"], "category": "anime", "desc": "Tropezar."},
    {"name": "stare", "alias": ["observar"], "category": "anime", "desc": "Mirar fijamente."},
    {"name": "sniff", "alias": ["olfatear"], "category": "anime", "desc": "Olfatear."},
    {"name": "curious", "alias": ["curioso"], "category": "anime", "desc": "Curiosidad."},
    {"name": "comfort", "alias": ["consolar"], "category": "anime", "desc": "Consolar."},
    {"name": "peek", "alias": ["espiar"], "category": "anime", "desc": "Espiar."},

    // --- 🔎 Búsquedas ---
    {"name": "pinterest", "alias": ["pin"], "category": "search", "desc": "Buscar Pinterest."},
    {"name": "imagen", "alias": ["img", "image"], "category": "search", "desc": "Buscar Google."},
    {"name": "aptoide", "alias": ["apk", "apkdl"], "category": "search", "desc": "Apps Aptoide."},
    {"name": "ytsearch", "alias": ["yts"], "category": "search", "desc": "Buscar YouTube."},
    {"name": "tiktoksearch", "alias": ["ttsearch", "tsearch"], "category": "search", "desc": "Buscar TikTok."},
    {"name": "tts", "alias": ["texttospeech"], "category": "search", "desc": "Texto a voz."},

    // --- 📥 Descargas ---
    {"name": "facebook", "alias": ["fb"], "category": "download", "desc": "Descargar FB."},
    {"name": "instagram", "alias": ["ig", "igdl", "instadl"], "category": "download", "desc": "Descargar IG."},
    {"name": "tiktok", "alias": ["tt", "tiktokdl", "ttdl"], "category": "download", "desc": "Descargar TT."},
    {"name": "play", "alias": ["play2", "mp3", "mp4", "ytmp3", "ytmp4"], "category": "download", "desc": "Descargar YT."},
    {"name": "song", "alias": ["yta", "ytaudio", "video", "ytv", "ytvideo"], "category": "download", "desc": "Audio/Video directo de YT."},
    {"name": "spotify", "alias": ["spot"], "category": "download", "desc": "Descargar Spotify."},
    {"name": "mediafire", "alias": ["mf"], "category": "download", "desc": "Mediafire."},
    {"name": "mega", "alias": ["mg"], "category": "download", "desc": "Mega."},
    {"name": "modapk", "alias": ["apkmod"], "category": "download", "desc": "APK Mod."},
    {"name": "twitter", "alias": ["x", "xtt", "xtwitter"], "category": "download", "desc": "Twitter/X."},
    {"name": "gitclone", "alias": ["git"], "category": "download", "desc": "Git Clone."},
    {"name": "drive", "alias": ["gdrive"], "category": "download", "desc": "Google Drive."},

    // --- 💰 Economía ---
    {"name": "balance", "alias": ["bal"], "category": "economia", "desc": "Ver dinero."},
    {"name": "steal", "alias": ["rob", "robar"], "category": "economia", "desc": "Robar dinero."},
    {"name": "crime", "alias": ["crimen"], "category": "economia", "desc": "Cometer crimen."},
    {"name": "givecoins", "alias": ["pay", "coinsgive", "darplata", "transfer"], "category": "economia", "desc": "Transferir."},
    {"name": "ppt", "alias": ["piedrapapeltijera"], "category": "economia", "desc": "Piedra Papel Tijera."},
    {"name": "math", "alias": ["matematicas"], "category": "economia", "desc": "Resolver mates."},
    {"name": "waittimes", "alias": ["cooldowns", "einfo", "economyinfo"], "category": "economia", "desc": "Ver tiempos."},
    {"name": "economyboard", "alias": ["baltop", "eboard"], "category": "economia", "desc": "Top Ricos."},
    {"name": "slut", "alias": [], "category": "economia", "desc": "Trabajo +18."},
    {"name": "mine", "alias": ["minar"], "category": "economia", "desc": "Minar."},
    {"name": "rt", "alias": ["roulette", "ruleta"], "category": "economia", "desc": "Ruleta."},
    {"name": "coinflip", "alias": ["flip", "cf"], "category": "economia", "desc": "Cara o Cruz."},
    {"name": "daily", "alias": ["diario"], "category": "economia", "desc": "Diario."},
    {"name": "monthly", "alias": ["mensual"], "category": "economia", "desc": "Mensual."},
    {"name": "weekly", "alias": ["semanal"], "category": "economia", "desc": "Semanal."},
    {"name": "work", "alias": ["w", "trabajar"], "category": "economia", "desc": "Trabajar."},
    {"name": "deposit", "alias": ["dep", "d"], "category": "economia", "desc": "Depositar."},
    {"name": "withdraw", "alias": ["with", "retirar"], "category": "economia", "desc": "Retirar."},
    {"name": "logros", "alias": [], "category": "economia", "desc": "Ver logros."},
    {"name": "toplogros", "alias": [], "category": "economia", "desc": "Top logros."},

    // --- 🎲 Gacha ---
    {"name": "rw", "alias": ["roll", "rollwaifu", "rf"], "category": "gacha", "desc": "Girar waifu."},
    {"name": "c", "alias": ["claim", "buy"], "category": "gacha", "desc": "Reclamar waifu."},
    {"name": "harem", "alias": ["miswaifus", "claims"], "category": "gacha", "desc": "Colección."},
    {"name": "sell", "alias": ["vender", "removesale"], "category": "gacha", "desc": "Vender waifu."},
    {"name": "buyc", "alias": ["buycharacter", "buychar"], "category": "gacha", "desc": "Comprar waifu."},
    {"name": "trade", "alias": ["cambiar"], "category": "gacha", "desc": "Intercambiar."},
    {"name": "animelist", "alias": ["slist", "serielist"], "category": "gacha", "desc": "Lista series."},
    {"name": "animeinfo", "alias": ["ainfo", "serieinfo"], "category": "gacha", "desc": "Info anime."},
    {"name": "tiendawaifus", "alias": ["wshop", "haremshop"], "category": "gacha", "desc": "Tienda."},
    {"name": "delrw", "alias": ["delwaifu", "delp"], "category": "gacha", "desc": "Borrar waifu."},
    {"name": "removerventa", "alias": ["retirarventa"], "category": "gacha", "desc": "Quitar venta."},
    {"name": "darrw", "alias": ["givewaifu", "givechar"], "category": "gacha", "desc": "Regalar waifu."},
    {"name": "giveallharem", "alias": [], "category": "gacha", "desc": "Regalar todo."},
    {"name": "ginfo", "alias": ["infogacha", "gachainfo"], "category": "gacha", "desc": "Info gacha."},
    {"name": "verpersonaje", "alias": ["vp"], "category": "gacha", "desc": "Ver personaje."},
    {"name": "character", "alias": ["charinfo", "cinfo"], "category": "gacha", "desc": "Info carta."},
    {"name": "vote", "alias": ["votar"], "category": "gacha", "desc": "Votar waifu."},
    {"name": "accepttrade", "alias": ["aceptarintercambio"], "category": "gacha", "desc": "Aceptar cambio."},
    {"name": "waifusboard", "alias": ["waifustop", "toprw"], "category": "gacha", "desc": "Top Gacha."},
    {"name": "votesboard", "alias": ["topvotos", "topwaifus"], "category": "gacha", "desc": "Top Votos."},
    {"name": "wimage", "alias": ["charimage", "cimage"], "category": "gacha", "desc": "Imagen Carta."},
    {"name": "robarwaifu", "alias": ["robarwaifu", "stealwaifu", "stealchar"], "category": "gacha", "desc": "Robar waifu"},

    // --- 👥 Grupo ---
    {"name": "mute", "alias": ["silenciar"], "category": "grupo", "desc": "Silenciar bot."},
    {"name": "promote", "alias": ["admin", "daradmin"], "category": "grupo", "desc": "Dar admin."},
    {"name": "demote", "alias": ["quitaradmin"], "category": "grupo", "desc": "Quitar admin."},
    {"name": "transfer", "alias": [], "category": "grupo", "desc": "Transferir propiedad."},
    {"name": "setprimary", "alias": [], "category": "grupo", "desc": "Bot primario."},
    {"name": "setgpbaner", "alias": ["setgpbanner"], "category": "grupo", "desc": "Foto grupo."},
    {"name": "setgpname", "alias": ["setname"], "category": "grupo", "desc": "Nombre grupo."},
    {"name": "setgpdesc", "alias": [], "category": "grupo", "desc": "Desc grupo."},
    {"name": "closet", "alias": ["cerrar"], "category": "grupo", "desc": "Cerrar grupo."},
    {"name": "open", "alias": ["abrir"], "category": "grupo", "desc": "Abrir grupo."},
    {"name": "delete", "alias": ["del"], "category": "grupo", "desc": "Borrar mensaje."},
    {"name": "on", "alias": ["welcome", "antilink", "nsfw", "rpg", "economia"], "category": "grupo", "desc": "Activar."},
    {"name": "off", "alias": [], "category": "grupo", "desc": "Desactivar."},
    {"name": "groupinfo", "alias": ["gp", "infogrupo"], "category": "grupo", "desc": "Info grupo."},
    {"name": "tag", "alias": ["hidetag", "notificar"], "category": "grupo", "desc": "Mencionar todos."},
    {"name": "kick", "alias": ["ban", "echar"], "category": "grupo", "desc": "Expulsar."},
    {"name": "warn", "alias": ["advertir", "warns"], "category": "grupo", "desc": "Advertencias."},
    {"name": "delwarn", "alias": [], "category": "grupo", "desc": "Quitar advertencia."},
    {"name": "link", "alias": ["enlace"], "category": "grupo", "desc": "Link grupo."},

    // --- 🧠 IA ---
    {"name": "ia", "alias": ["chatgpt", "gpt", "lucoa"], "category": "ia", "desc": "Chat con Lucoa."},
    {"name": "dalle", "alias": ["iaimg", "aiimage", "genimg"], "category": "ia", "desc": "Imagen IA."},
    {"name": "aigensfw", "alias": ["nsfwaigen", "pornogen", "ainsfw"], "category": "ia", "desc": "Imagen IA +18."},

    // --- ℹ️ Información ---
    {"name": "menu", "alias": ["help", "comandos", "menú"], "category": "info", "desc": "Ver menú."},
    {"name": "infobot", "alias": ["infosocket", "status"], "category": "info", "desc": "Estado bot."},
    {"name": "ping", "alias": ["p", "velocidad"], "category": "info", "desc": "Ver ping."},
    {"name": "report", "alias": ["reporte"], "category": "info", "desc": "Reportar error."},
    {"name": "suggest", "alias": ["sug"], "category": "info", "desc": "Sugerencia."},
    {"name": "invite", "alias": ["invitar"], "category": "info", "desc": "Invitar bot."},
    {"name": "owner", "alias": ["creador", "contacto", "cafi", "cafirexos"], "category": "info", "desc": "Dueño."},
    {"name": "hosting", "alias": [], "category": "info", "desc": "Info hosting."},

    // --- 🔞 NSFW (+18) ---
    {"name": "danbooru", "alias": ["dbooru"], "category": "nsfw", "desc": "Danbooru."},
    {"name": "gelbooru", "alias": ["gbooru"], "category": "nsfw", "desc": "Gelbooru."},
    {"name": "rule34", "alias": ["r34"], "category": "nsfw", "desc": "Rule34."},
    {"name": "hentai", "alias": [], "category": "nsfw", "desc": "Imagen Hentai."},
    {"name": "xVideos", "alias": ["xnxx", "xvideos"], "category": "nsfw", "desc": "Videos XXX."},
    {"name": "anal", "alias": [], "category": "nsfw", "desc": "Anal."},
    {"name": "cum", "alias": ["leche", "venirse"], "category": "nsfw", "desc": "Cumshot."},
    {"name": "undress", "alias": ["encuerar", "desnudar"], "category": "nsfw", "desc": "Desnudar."},
    {"name": "fuck", "alias": ["coger", "follar"], "category": "nsfw", "desc": "Follar."},
    {"name": "spank", "alias": ["nalgada", "azotar"], "category": "nsfw", "desc": "Nalgada."},
    {"name": "lickpussy", "alias": ["lamercoño"], "category": "nsfw", "desc": "Lamer."},
    {"name": "fap", "alias": ["paja", "dedear", "fingering"], "category": "nsfw", "desc": "Masturbación."},
    {"name": "grope", "alias": ["manosear", "toquetear"], "category": "nsfw", "desc": "Manosear."},
    {"name": "sixnine", "alias": ["69"], "category": "nsfw", "desc": "69."},
    {"name": "suckboobs", "alias": ["chupartetas"], "category": "nsfw", "desc": "Chupar tetas."},
    {"name": "grabboobs", "alias": ["agarrartetas"], "category": "nsfw", "desc": "Agarrar tetas."},
    {"name": "blowjob", "alias": ["bj", "mamada"], "category": "nsfw", "desc": "Mamada."},
    {"name": "boobjob", "alias": ["rusa"], "category": "nsfw", "desc": "Rusa."},
    {"name": "footjob", "alias": ["pies"], "category": "nsfw", "desc": "Pies."},
    {"name": "hentaivid", "alias": ["hentaivideo"], "category": "nsfw", "desc": "Video Hentai."},
    {"name": "yuri", "alias": ["imagenlesbians"], "category": "nsfw", "desc": "Yuri."},
    {"name": "pene", "alias": [], "category": "nsfw", "desc": "Pene."},
    {"name": "culo", "alias": [], "category": "nsfw", "desc": "Culo."},
    {"name": "tetas", "alias": [], "category": "nsfw", "desc": "Tetas."},
    {"name": "orgy", "alias": ["orgia", "trio", "threesome", "gangbang"], "category": "nsfw", "desc": "Orgía."},
    {"name": "bdsm", "alias": ["bondage", "amarrar", "atar"], "category": "nsfw", "desc": "BDSM."},
    {"name": "ecchi", "alias": [], "category": "nsfw", "desc": "Ecchi."},
    {"name": "panties", "alias": ["ropainterior"], "category": "nsfw", "desc": "Ropa interior."},
    {"name": "tentacle", "alias": ["tentaculos"], "category": "nsfw", "desc": "Tentáculos."},
    {"name": "nsfwloli", "alias": [], "category": "nsfw", "desc": "Loli H."},
    {"name": "nsfwfoot", "alias": [], "category": "nsfw", "desc": "Pies H."},

    // --- 👤 Perfil ---
    {"name": "level", "alias": ["lvl", "levelup"], "category": "profile", "desc": "Nivel."},
    {"name": "marry", "alias": ["casarse"], "category": "profile", "desc": "Casarse."},
    {"name": "divorce", "alias": ["divorcio"], "category": "profile", "desc": "Divorciarse."},
    {"name": "profile", "alias": ["perfil"], "category": "profile", "desc": "Ver perfil."},
    {"name": "setbirth", "alias": [], "category": "profile", "desc": "Poner cumple."},
    {"name": "delbirth", "alias": [], "category": "profile", "desc": "Borrar cumple."},
    {"name": "setdescription", "alias": ["setdesc", "setbio"], "category": "profile", "desc": "Poner bio."},
    {"name": "deldescription", "alias": ["deldesc"], "category": "profile", "desc": "Borrar bio."},
    {"name": "setgenre", "alias": [], "category": "profile", "desc": "Poner género."},
    {"name": "delgenre", "alias": [], "category": "profile", "desc": "Borrar género."},
    {"name": "sethobby", "alias": ["setpasatiempo"], "category": "profile", "desc": "Poner hobby."},
    {"name": "removehobby", "alias": ["delpasatiempo"], "category": "profile", "desc": "Borrar hobby."},

    // --- 🤖 Sub-Bots ---
    {"name": "bots", "alias": ["sockets"], "category": "sockets", "desc": "Lista bots."},
    {"name": "logout", "alias": ["logout2", "clearsubs", "stop"], "category": "sockets", "desc": "Apagar bot."},
    {"name": "qr", "alias": ["code", "jadibot"], "category": "sockets", "desc": "Ser bot (QR)."},
    {"name": "qrpremium", "alias": ["codepremium"], "category": "sockets", "desc": "QR Premium."},
    {"name": "qrmod", "alias": ["codemod"], "category": "sockets", "desc": "QR Mod."},
    {"name": "self", "alias": [], "category": "sockets", "desc": "Modo privado."},
    {"name": "set", "alias": ["edit"], "category": "sockets", "desc": "Editar bot."},
    {"name": "leave", "alias": [], "category": "sockets", "desc": "Salir grupo."},
    {"name": "setname", "alias": ["setbotname"], "category": "sockets", "desc": "Nombre bot."},
    {"name": "setprefix", "alias": ["setbotprefix"], "category": "sockets", "desc": "Prefijo bot."},
    {"name": "seticon", "alias": ["setpfp"], "category": "sockets", "desc": "Icono bot."},
    {"name": "setbio", "alias": ["setstatus"], "category": "sockets", "desc": "Bio bot."},

    // --- 🛠️ Utilidades ---
    {"name": "sticker", "alias": ["s"], "category": "utils", "desc": "Sticker."},
    {"name": "getpic", "alias": ["pfp"], "category": "utils", "desc": "Foto perfil."},
    {"name": "tourl", "alias": ["upload"], "category": "utils", "desc": "Subir URL."},
    {"name": "translate", "alias": ["tr"], "category": "utils", "desc": "Traducir."},
    {"name": "get", "alias": [], "category": "utils", "desc": "Ver código."},
    {"name": "setmeta", "alias": [], "category": "utils", "desc": "Meta sticker."},
    {"name": "hd", "alias": ["upscale"], "category": "utils", "desc": "Mejorar calidad."},
    {"name": "rvocal", "alias": [], "category": "utils", "desc": "Quitar voz."},
    {"name": "wm", "alias": [], "category": "utils", "desc": "Marca de agua."},
    {"name": "confesión", "alias": ["confesar"], "category": "utils", "desc": "Confesión."},
    {"name": "responder", "alias": [], "category": "utils", "desc": "Responder."},
    {"name": "setalias", "alias": [], "category": "utils", "desc": "Alias usuario."},
    {"name": "delalias", "alias": [], "category": "utils", "desc": "Borrar alias."},
    {"name": "tofigure", "alias": ["tf"], "category": "utils", "desc": "Sticker silueta."},
    {"name": "qc", "alias": [], "category": "utils", "desc": "Sticker texto."},
    
    // --- 🌀 RPG / Juegos ---
    {"name": "ahorcado", "alias": ["hangman"], "category": "rpg", "desc": "Ahorcado."},

    // --- 🌀 Otros ---
    {"name": "eval", "alias": ["=>"], "category": "otros", "desc": "Evaluar JS."},
    {"name": "exec", "alias": ["$"], "category": "otros", "desc": "Terminal."},
    {"name": "restart", "alias": ["update"], "category": "otros", "desc": "Reiniciar."},
    {"name": "fix", "alias": ["clean"], "category": "otros", "desc": "Limpiar sesión."}
]
